[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0xc0251812fce795c01c629a792d4f7d8588442ea45bf48efaff3c72ce30474286'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
